image: gcc:7.5.0

before_script:
    - umask 000
    - apt-get update --yes
    - apt-get install --yes lcov
    - apt-get install --yes cmake
    - git clone https://github.com/google/googletest.git
    - cd googletest/ 
    - cmake .
    - cmake --build .
    - cd ..



build:
  stage: build
  script: 
    - cmake .
    - cmake --build .
    - cmake -DCMAKE_BUILD_TYPE=Debug .
    - ls -l
    - ./proxytcp_tests
    - lcov --rc lcov_branch_coverage=1 --no-external -d "." --capture -o proxytcp_tests.info -c 
    - lcov --rc lcov_branch_coverage=1 --remove proxytcp_tests.info '/builds/xplainmeplease/proxytcp/Tests/*' '/builds/xplainmeplease/proxytcp/googletest/*' -o filtered.info
    - ls -l
    - genhtml -o coverage filtered.info
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 30 days

test:
  stage: test
  only: 
    - merge_request
  script:
    - ls 
    - cmake .
    - cmake --build .
    - ./proxytcp_tests



