    dist: bionic
    sudo: false
    language: cpp
    os: linux
    

    before_script:
    - umask 000
    - sudo apt-get update --yes
    - sudo apt-get install --yes lcov
    - sudo apt-get install --yes cmake
    - sudo git clone https://github.com/google/googletest.git
    - cd googletest/ 
    - sudo cmake .
    - sudo cmake --build .
    - cd ..

    script: 
    - ls -l
    - sudo sh LaunchCoverage.sh "/home/travis/build/vizhyk"
    after_success:
    - cd CodeCoverage
    - export CODECOV_TOKEN="f720a65e-f3e7-48d2-afa7-193a211c9062"
    - bash <(curl -s https://codecov.io/bash) -f filtered.info 
